# -*- coding: utf-8 -*-
"""Data_Audio_Fundementals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/luqman-x/Pytorch-Practices/blob/main/ICBHI%20Respiratory%20Classifier/Data_Audio_Fundementals.ipynb
"""

import os
import shutil
import numpy as np
import pandas as pd
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from pathlib import Path
from collections import Counter
from IPython.display import Audio, display

from google.colab import drive
drive.mount('/content/drive')

CONFIG = {
    "raw_dir"    : "/content/icbhi_dataset/raw/Respiratory_Sound_Database/Respiratory_Sound_Database",      # downloaded .wav + .txt
    "cycles_dir" : "/content/icbhi_dataset/cycles",   # segmented cycles go here
    "splits_file": "/content/icbhi_dataset/raw/ICBHI_challenge_train_test.txt",


    "target_sr"  : 22050,

    "class_map" : {
        (0,0): "Normal",
        (1,0): "Crackle",
        (0,1): "Wheeze",
        (1,1): "Both",
    },
    "classes"    : ["Normal", "Crackle", "Wheeze", "Both"],

    "seed" : 42,

}

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d vbookshelf/respiratory-sound-database \
       -p /content/icbhi_dataset/raw --unzip --quiet

print("Download complete.")

def parse_annotation_file(txt_path: str) -> pd.DataFrame:
  """
    Read one ICBHI annotation .txt file and return a DataFrame.

    Args:
        txt_path: path to the .txt annotation file

    Returns:
        DataFrame with columns:
            start    → cycle start time in seconds (float)
            end      → cycle end time in seconds (float)
            crackle  → 1 if crackles present, else 0 (int)
            wheeze   → 1 if wheeze present, else 0 (int)
            label    → human-readable class string ("Normal", "Crackle", etc.)
    """

  df = pd.read_csv(
        txt_path,
        sep="\t",
        header=None,
        names=["start", "end", "crackle", "wheeze"],
    )
  df["crackle"] = df["crackle"].astype(int)
  df["wheeze"] = df["wheeze"].astype(int)


  df["label"] = df.apply(
        lambda row: CONFIG["class_map"][(row["crackle"], row["wheeze"])],
        axis=1
    )

  return df

def demo_annotation_parsing(raw_dir: str):
    """Show the first annotation file we find."""
    audio_dir = os.path.join(raw_dir, "audio_and_txt_files")

    # Find any .txt file
    txt_files = list(Path(audio_dir).glob("*.txt"))
    if not txt_files:
        print("No annotation files found. Check your raw_dir path.")
        return

    sample_txt = str(txt_files[0])
    print(f"Parsing: {os.path.basename(sample_txt)}\n")

    df = parse_annotation_file(sample_txt)
    print(df.to_string(index=False))
    print(f"\nCycles in this recording: {len(df)}")
    print(f"Label counts: {df['label'].value_counts().to_dict()}")

demo_annotation_parsing(CONFIG["raw_dir"])

def build_master_annotation(raw_dir: str, splits_file: str) -> pd.DataFrame:
  """
    Parse all annotation files and combine into one master DataFrame.

    Also attaches:
        - patient_id  → extracted from filename (first number, e.g. "101")
        - split       → "train" or "test" from official ICBHI split file
        - wav_path    → full path to the source .wav file
        - txt_path    → full path to the annotation .txt file

    Args:
        raw_dir     : path to the raw dataset root
        splits_file : path to ICBHI_challenge_train_test.txt

    Returns:
        master DataFrame with one row per breathing cycle
    """
  audio_dir = os.path.join(raw_dir, "audio_and_txt_files")
   # The split file has one filename per line, labeled "train" or "test"
  # Format:  101_1b1_Al_sc_Litt3200   train
  split_df = pd.read_csv(
      splits_file,
      sep="\t",
      header=None,
      names=["filename", "split"]
  )
  print("\n--- Split file content (first 5 rows):\n", split_df.head())

  # Build a dict: filename_stem → "train" or "test"
  split_dict = dict(zip(split_df["filename"], split_df["split"]))

  all_rows = []   # collect rows from every file

  txt_files = sorted(Path(audio_dir).glob("*.txt"))
  print(f"\nFound {len(txt_files)} annotation files...")

  # Limit to first few files for inspection
  _debug_count = 0
  for txt_path in txt_files:
      stem = txt_path.stem               # e.g. "101_1b1_Al_sc_Litt3200"
      wav_path = txt_path.with_suffix(".wav")  # matching .wav file

      if not wav_path.exists():
          # Skip if audio file missing (shouldn't happen in clean download)
          print(f"  WARNING: No .wav found for {stem}, skipping.")
          continue

      # Extract patient ID — always the first part before the first underscore
      patient_id = stem.split("_")[0]    # "101_1b1_..." → "101"

      # Get train/test label from the split dict
      split = split_dict.get(stem, "unknown")

      if _debug_count < 5: # Print first 5 stems and their resolved split
          print(f"  Debug: Stem '{stem}' resolved to split '{split}'")
          _debug_count += 1

      # Parse this file's annotation
      df = parse_annotation_file(str(txt_path))

      # Attach metadata columns to every row
      df["filename"]   = stem
      df["patient_id"] = patient_id
      df["split"]      = split
      df["wav_path"]   = str(wav_path)
      df["txt_path"]   = str(txt_path)

      all_rows.append(df)

  # Stack all individual DataFrames into one master table
  master = pd.concat(all_rows, ignore_index=True)

  # Add a unique cycle_id for each row (useful for saving files later)
  master["cycle_id"] = master.index

  print(f"\nMaster DataFrame built.")
  print(f"Total breathing cycles : {len(master)}")
  print(f"Unique patients        : {master['patient_id'].nunique()}")
  print(f"Train cycles           : {(master['split'] == 'train').sum()}")
  print(f"Test cycles            : {(master['split'] == 'test').sum()}")

  return master

from pathlib import Path
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

url = (
    "https://bhichallenge.med.auth.gr/sites/default/files/"
    "ICBHI_final_database/ICBHI_challenge_train_test.txt"
)

split_path = Path("/content/icbhi_dataset/raw/ICBHI_challenge_train_test.txt")

response = requests.get(
    url,
    verify=False,       # Required because the server certificate is expired
    timeout=60
)

response.raise_for_status()

content = response.content

# Prevent accidentally saving another HTML error page
text_start = content[:1000].lower()
if b"<html" in text_start or b"<!doctype" in text_start:
    raise RuntimeError(
        "The server returned an HTML error page instead of the split file."
    )

split_path.write_bytes(content)

print("Downloaded:", split_path)
print("Size:", split_path.stat().st_size, "bytes")

master_df = build_master_annotation(CONFIG["raw_dir"], CONFIG["splits_file"])

from pathlib import Path

print(Path(split_path).read_text(encoding="utf-8")[:500])

import pandas as pd

split_df = pd.read_csv(
    split_path,
    sep=r"\s+",
    header=None,
    names=["filename", "split"]
)

print(split_df.head(10))
print()
print(split_df["split"].value_counts())

# or use this
"""
!wget --no-check-certificate \
  -O /content/icbhi_dataset/raw/ICBHI_challenge_train_test.txt \
  "https://bhichallenge.med.auth.gr/sites/default/files/ICBHI_final_database/ICBHI_challenge_train_test.txt"
"""

"""
  !head -10 /content/icbhi_dataset/raw/ICBHI_challenge_train_test.txt
"""

master_df = build_master_annotation(
    CONFIG["raw_dir"],
    CONFIG["splits_file"]
)

def plot_class_distribution(master_df: pd.DataFrame):
    """
    Plot class counts for train and test splits side by side.
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("ICBHI 2017 — Class Distribution per Split", fontsize=14, fontweight="bold")

    colors = {
        "Normal" : "#4CAF50",   # green — healthy
        "Crackle": "#FF9800",   # orange — abnormal
        "Wheeze" : "#F44336",   # red — abnormal
        "Both"   : "#9C27B0",   # purple — most severe
    }

    for ax, split in zip(axes, ["train", "test"]):
        split_df = master_df[master_df["split"] == split]
        counts   = split_df["label"].value_counts()

        # Reorder to match CONFIG["classes"] order
        counts = counts.reindex(CONFIG["classes"], fill_value=0)

        bars = ax.bar(
            counts.index,
            counts.values,
            color=[colors[c] for c in counts.index],
            edgecolor="white",
            linewidth=1.2
        )

        # Annotate each bar with its count and percentage
        total = counts.sum()
        for bar, count in zip(bars, counts.values):
            pct = 100 * count / total
            ax.text(
                bar.get_x() + bar.get_width() / 2,  # x: center of bar
                bar.get_height() + 30,               # y: just above bar
                f"{count}\n({pct:.1f}%)",            # label text
                ha="center", va="bottom", fontsize=9
            )

        ax.set_title(f"{split.capitalize()} Split  (n={total})", fontsize=12)
        ax.set_ylabel("Number of Cycles")
        ax.set_ylim(0, counts.max() * 1.25)   # headroom for annotations
        ax.spines[["top", "right"]].set_visible(False)

    plt.tight_layout()
    plt.savefig("class_distribution.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("\nKey observation: Normal >> Crackle >> Wheeze >> Both")
    print("This imbalance is WHY WeightedRandomSampler + SpecAugment will be needed.")

plot_class_distribution(master_df)

def demonstrate_audio_loading(wav_path: str, target_sr: int = 22050):
    """
    Load one .wav file and explain what librosa gives you.

    Args:
        wav_path  : path to any .wav file in the dataset
        target_sr : the sample rate to resample to
    """
    y, sr = librosa.load(
        wav_path,
        sr = target_sr,
        mono=True
    )

    duration = len(y) / sr   # total duration in seconds

    print("=" * 10)
    print(f"File          : {os.path.basename(wav_path)}")
    print(f"Sample rate   : {sr} Hz")
    print(f"Num samples   : {len(y):,}")
    print(f"Duration      : {duration:.2f} seconds")
    print(f"y dtype       : {y.dtype}")
    print(f"y min/max     : {y.min():.4f} / {y.max():.4f}")
    print(f"y shape       : {y.shape}")
    print("=" * 10)
    print("\nIntuition:")
    print(f"  {sr} samples/sec × {duration:.1f} sec = {len(y):,} numbers")
    print(f"  Each number = air pressure at that instant (range: -1.0 to +1.0)")

    # Play the audio directly in Colab
    print("\nPlaying audio in Colab...")
    display(Audio(y, rate=sr))
    return y, sr

sample_wav_path = master_df['wav_path'].iloc[0]
target_sr = CONFIG['target_sr']

y, sr = demonstrate_audio_loading(wav_path=sample_wav_path, target_sr=target_sr)

import os

# PART 7 — BREATHING CYCLE SEGMENTATION

# The ICBHI labels are per CYCLE, not per full recording.
# A full recording might be 20 seconds with 8 breathing cycles.
# We need to slice each cycle into its own audio clip.

def segment_and_save_cycles(master_df: pd.DataFrame, cycles_dir: str, target_sr: int):
  """
    For every row in master_df (= every breathing cycle):
        1. Load the source .wav
        2. Slice the audio between start_time and end_time
        3. Save as a new .wav file in cycles_dir/split/label/

    This creates the folder structure  needed for ImageFolder later
    (after Phase 2 converts these to spectrograms).

    Args:
        master_df  : the master DataFrame from build_master_dataframe()
        cycles_dir : where to save segmented cycle .wav files
        target_sr  : sample rate to save at
    """
  # Cache loaded audio files to avoid re-reading the same .wav repeatedly.
  # One recording can have 8+ cycles — no need to reload 8 times.
  audio_cache = {}

  saved   = 0
  skipped = 0

  for _, row in master_df.iterrows():
        # ── Build the output path ─────────────────────────────────────────
        # Structure: cycles_dir / split / label / filename_cycleID.wav
        # Example:   cycles/train/Crackle/101_1b1_Al_sc_Litt3200_cycle003.wav
    out_dir = os.path.join(cycles_dir, row["split"], row["label"])
    os.makedirs(out_dir, exist_ok=True)

    cycle_filename = f"{row['filename']}_cycle{row['cycle_id']:04d}.wav"
    out_path = os.path.join(out_dir, cycle_filename)

    if os.path.exists(out_path):
        # Skip if already saved (resume-safe, same pattern as your CNN phases)
        skipped += 1
        continue

        # ── Load audio (from cache if already loaded) ─────────────────────
    wav_path = row["wav_path"]
    if wav_path not in audio_cache:
        y, sr = librosa.load(wav_path, sr=target_sr, mono=True)
        audio_cache[wav_path] = (y, sr)
    else:
        y, sr = audio_cache[wav_path]

        # ── Slice the cycle ───────────────────────────────────────────────
        # Convert timestamps (seconds) → sample indices
    start_sample = int(row["start"] * sr)   # e.g. 0.036s × 22050 = 794
    end_sample   = int(row["end"]   * sr)   # e.g. 1.154s × 22050 = 25456

    cycle_audio = y[start_sample:end_sample]  # numpy slice = fast

    # Skip cycles that are too short (< 0.5s) — likely annotation errors
    min_samples = int(0.5 * sr)   # 0.5 seconds × 22050 = 11025 samples
    if len(cycle_audio) < min_samples:
        skipped += 1
        continue

        # ── Save the cycle ────────────────────────────────────────────────
    sf.write(out_path, cycle_audio, sr)   # soundfile handles wav encoding
    saved += 1

  print(f"\nSegmentation complete.")
  print(f"Saved   : {saved} cycles")
  print(f"Skipped : {skipped} cycles (already exist or too short)")

  # Show what the folder structure looks like
  print("\nFolder structure created:")
  for split in ["train", "test"]:
    for label in CONFIG["classes"]:
      folder = os.path.join(cycles_dir, split, label)
      if os.path.exists(folder):
        n = len(os.listdir(folder))
        print(f"  {split}/{label:<8} → {n} cycles")

segment_and_save_cycles(master_df, CONFIG["cycles_dir"], CONFIG["target_sr"])

# PART 8 — WAVEFORM VISUALIZATION (THE KEY LEARNING MOMENT)
# =============================================================================
# Now you see WHY different diseases look different in audio.
#
# CRACKLES: short, explosive discontinuous sounds
#   → Waveform shows sharp spikes at irregular intervals
#   → Caused by: sudden opening of closed airways (pneumonia, fibrosis)
#
# WHEEZES: continuous musical tones
#   → Waveform shows sustained oscillation (like a sine wave)
#   → Caused by: narrowed airways vibrating (asthma, COPD)
#
# NORMAL: smooth, quiet, rhythmic breathing
#   → Waveform shows low-amplitude gentle oscillations

def plot_waveforms_by_class(cycles_dir: str, target_sr: int, num_examples: int = 2):
    """
    Plot sample waveforms for each class side by side.
    This is your intuition-building moment for the audio domain.

    Args:
        cycles_dir   : path to segmented cycles folder
        target_sr    : sample rate
        num_examples : how many examples to show per class
    """
    fig, axes = plt.subplots(
        len(CONFIG["classes"]), num_examples,
        figsize=(14, 4 * len(CONFIG["classes"]))
    )
    fig.suptitle(
        "Lung Sound Waveforms — What Each Class Looks Like in Time Domain",
        fontsize=13, fontweight="bold", y=1.01
    )

    class_descriptions = {
        "Normal" : "Smooth, quiet, rhythmic oscillations",
        "Crackle": "Sharp explosive spikes — sudden airway openings",
        "Wheeze" : "Sustained oscillation — narrowed airway vibration",
        "Both"   : "Combination of spikes and sustained oscillation",
    }

    np.random.seed(CONFIG["seed"])

    for row_idx, label in enumerate(CONFIG["classes"]):
        # Find available cycle files for this class (train split)
        class_folder = os.path.join(cycles_dir, "train", label)
        if not os.path.exists(class_folder):
            print(f"  No samples found for {label} yet. Run segmentation first.")
            continue

        wav_files = list(Path(class_folder).glob("*.wav"))
        if not wav_files:
            continue

        # Pick random examples
        chosen = np.random.choice(
            wav_files,
            size=min(num_examples, len(wav_files)),
            replace=False
        )

        for col_idx, wav_file in enumerate(chosen):
            ax = axes[row_idx][col_idx]

            # Load this cycle
            y, sr = librosa.load(str(wav_file), sr=target_sr)

            # Time axis in seconds
            time_axis = np.linspace(0, len(y) / sr, num=len(y))

            # Plot the waveform
            ax.plot(
                time_axis, y,
                linewidth=0.5,
                color=["#4CAF50","#FF9800","#F44336","#9C27B0"][row_idx],
                alpha=0.8
            )
            ax.set_xlim(0, len(y) / sr)
            ax.set_ylim(-1.0, 1.0)   # amplitude always in [-1, 1] after librosa

            # Labels
            if col_idx == 0:
                ax.set_ylabel(f"{label}\n{class_descriptions[label]}", fontsize=9)
            if row_idx == len(CONFIG["classes"]) - 1:
                ax.set_xlabel("Time (seconds)")

            ax.set_title(f"Example {col_idx + 1}", fontsize=9)
            ax.spines[["top", "right"]].set_visible(False)

    plt.tight_layout()
    plt.savefig("waveforms_by_class.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("\nStudy these waveforms carefully before moving to Phase 2.")
    print("The patterns you see here will become visible features in mel-spectrograms.")

# PART 9 — AUDIO PLAYBACK IN COLAB
# =============================================================================
# Listen to actual lung sounds. This is important — understanding the domain
# through your ears makes you a better model designer.

def play_class_examples(cycles_dir: str, target_sr: int):
    """
    Play one audio example per class directly in Colab.
    Run this cell and listen carefully to each sound.
    """
    np.random.seed(CONFIG["seed"])

    for label in CONFIG["classes"]:
        class_folder = os.path.join(cycles_dir, "train", label)
        wav_files = list(Path(class_folder).glob("*.wav"))

        if not wav_files:
            print(f"{label}: no files found")
            continue

        chosen = np.random.choice(wav_files)
        y, sr = librosa.load(str(chosen), sr=target_sr)

        duration = len(y) / sr
        print(f"\n{'='*40}")
        print(f"Class    : {label}")
        print(f"File     : {os.path.basename(chosen)}")
        print(f"Duration : {duration:.2f}s")
        print(f"Listen   ↓")
        display(Audio(y, rate=sr))


# =============================================================================
# PART 10 — PHASE 1 SUMMARY: DATA STATISTICS REPORT
# =============================================================================

def phase1_summary_report(master_df: pd.DataFrame):
    """Print a clean summary of what Phase 1 produced."""

    print("\n" + "="*55)
    print("  PHASE 1 COMPLETE — DATA SUMMARY REPORT")
    print("="*55)

    total = len(master_df)
    print(f"\nTotal breathing cycles  : {total:,}")
    print(f"Unique patients         : {master_df['patient_id'].nunique()}")
    print(f"Unique recordings       : {master_df['filename'].nunique()}")

    print("\n── Class Distribution ────────────────────────────────")
    for label in CONFIG["classes"]:
        n   = (master_df["label"] == label).sum()
        pct = 100 * n / total
        bar = "█" * int(pct / 2)
        print(f"  {label:<8} {n:>5}  ({pct:5.1f}%)  {bar}")

    print("\n── Train / Test Split ────────────────────────────────")
    for split in ["train", "test"]:
        n   = (master_df["split"] == split).sum()
        pct = 100 * n / total
        print(f"  {split:<6}  {n:>5}  ({pct:.1f}%)")

    print("\n── Key Observations ──────────────────────────────────")
    print("  1. Normal cycles dominate (~53%) → class imbalance")
    print("  2. Wheeze + Both are minority classes (<10% combined)")
    print("  3. Split is by PATIENT (not cycle) → no data leakage")
    print("     (same patient never appears in both train and test)")
    print("\n  → These observations directly shape Phase 4 strategy:")
    print("    WeightedRandomSampler + SpecAugment on minority classes")

    print("\n── What Phase 2 Will Do ──────────────────────────────")
    print("  Convert every .wav cycle → mel-spectrogram → 224×224 PNG")
    print("  After Phase 2, this becomes a standard ImageFolder problem")
    print("  and your existing CNN pipeline takes over.")
    print("="*55)

audio_dir = os.path.join(CONFIG["raw_dir"], "audio_and_txt_files")
sample_wav = list(Path(audio_dir).glob("*.wav"))[0]
y, sr = demonstrate_audio_loading(str(sample_wav), CONFIG["target_sr"])
segment_and_save_cycles(master_df, CONFIG["cycles_dir"], CONFIG["target_sr"])
plot_waveforms_by_class(CONFIG["cycles_dir"], CONFIG["target_sr"])
play_class_examples(CONFIG["cycles_dir"], CONFIG["target_sr"])
phase1_summary_report(master_df)

